### ISSUE TITLE
need /n in install apache

### ISSUE THREAD

**Issue by BeMg** [henrybear327/Web-Learning-Notes#2]
Add  ServerSignature Off ServerTokens ProductOnly 

need change to

Add  ServerSignature Off 
ServerTokens ProductOnly 

the first will erorr, and add /n improve to let people know it is two line.

**Comment by henrybear327** [comment]
I wil fix it tomorrow thanks.

This is a formatting issue. :(

On Friday, 29 January 2016, BeMg notifications@github.com wrote:

> Add ServerSignature Off ServerTokens ProductOnly
> 
> need change to
> 
> Add ServerSignature Off
> ServerTokens ProductOnly
> 
> the first will erorr, and add /n improve to let people know it is two line.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/henrybear327/Web-Learning-Notes/issues/2.

## 

Best wishes,
Henry Tseng

**Comment by henrybear327** [comment]
error fixed
Thanks for telling me

The markdown rendering was ok on local machine's ATOM text editor though...
